# Generated by Django 2.1 on 2018-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpid', models.CharField(max_length=128, null=True)),
                ('corpsecret', models.CharField(max_length=64, null=True)),
                ('agentid', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=256, null=True)),
                ('expirestime', models.DateTimeField()),
            ],
            options={
                'db_table': 'base_conf',
            },
        ),
        migrations.CreateModel(
            name='hr_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('parentid', models.IntegerField(default=0)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'hr_department',
            },
        ),
        migrations.CreateModel(
            name='hr_hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('avatar', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('enable', models.IntegerField(default=1)),
                ('isleader', models.IntegerField(default=0)),
                ('extattr', models.CharField(max_length=256)),
                ('hide_mobile', models.BooleanField(default=0)),
                ('english_name', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=20)),
                ('order', models.CharField(max_length=256)),
                ('external_profile', models.CharField(max_length=256)),
                ('qr_code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='pureftp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=11)),
                ('gid', models.CharField(max_length=11)),
                ('dir', models.CharField(max_length=128)),
                ('ulbandwidth', models.IntegerField(default=0)),
                ('dlbandwidth', models.IntegerField(default=0)),
                ('comment', models.TextField(null=True)),
                ('ipaccess', models.CharField(default='0.0.0.0', max_length=15)),
                ('quotasize', models.IntegerField(default=0)),
                ('quotafiles', models.IntegerField(default=0)),
                ('createdate', models.DateField()),
                ('lastedate', models.DateField()),
            ],
        ),
    ]
