# Generated by Django 2.1.1 on 2018-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_property',
            name='sn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='出厂编号'),
        ),
    ]
