# Generated by Django 2.1 on 2018-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='crnu',
            field=models.IntegerField(default=1),
        ),
    ]
