# Generated by Django 2.0.6 on 2018-08-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='qr_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='个人二维码'),
        ),
    ]
