# Generated by Django 2.0.6 on 2018-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_hr',
            name='passwd',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
