# Generated by Django 2.1 on 2018-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180831_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='department',
            field=models.CharField(blank=True, max_length=256, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='enable',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='english_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='extattr',
            field=models.CharField(blank=True, max_length=256, verbose_name='扩展属性'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='external_profile',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='gender',
            field=models.CharField(blank=True, max_length=16, verbose_name='姓别'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='hide_mobile',
            field=models.BooleanField(blank=True, default=0, verbose_name='隐蔽手机'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='isleader',
            field=models.IntegerField(blank=True, default=0, verbose_name='主管'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='order',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='passwd',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='position',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='qr_code',
            field=models.CharField(blank=True, max_length=256, verbose_name='个人二维码'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='session',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Cookice_session'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='座机'),
        ),
    ]
