# Generated by Django 2.0.6 on 2018-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180810_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpid', models.CharField(max_length=128)),
                ('corpsecret', models.CharField(max_length=64)),
                ('agentid', models.IntegerField()),
                ('token', models.CharField(max_length=256)),
                ('expirestime', models.DateTimeField()),
            ],
            options={
                'db_table': 'base_conf',
            },
        ),
    ]
