# Generated by Django 2.1 on 2018-09-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_hr_hr_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_menu',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.base_menu', to_field='mnid', verbose_name='上级菜单'),
        ),
        migrations.AddField(
            model_name='base_menu',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='base_menu',
            name='active',
            field=models.FloatField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
        migrations.AlterModelTable(
            name='base_user_sign_log',
            table='base_user_log',
        ),
    ]
