# Generated by Django 2.1 on 2018-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180824_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='session',
            field=models.CharField(max_length=16, null=True, verbose_name='Cookice_session'),
        ),
    ]
