# Generated by Django 2.0.6 on 2018-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180901_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='department',
            field=models.CharField(max_length=256, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='enable',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='english_name',
            field=models.CharField(max_length=64, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='extattr',
            field=models.CharField(max_length=256, null=True, verbose_name='扩展属性'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='external_profile',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='gender',
            field=models.CharField(max_length=16, null=True, verbose_name='姓别'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='isleader',
            field=models.IntegerField(default=0, verbose_name='主管'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='order',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='position',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='座机'),
        ),
    ]
