# Generated by Django 2.1.1 on 2018-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181119_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='position',
            field=models.CharField(max_length=64, null=True, verbose_name='职务信息'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='status',
            field=models.IntegerField(default=1, verbose_name='激活状态'),
        ),
    ]
