# Generated by Django 2.0.6 on 2018-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_base_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_conf',
            name='agentid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='corpid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='corpsecret',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pureftp',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
