# Generated by Django 2.1 on 2018-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180828_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_hr',
            name='expsession',
            field=models.TimeField(null=True),
        ),
    ]
