# Generated by Django 2.0.6 on 2018-08-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180901_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='expsession',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='passwd',
            field=models.CharField(max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='qr_code',
            field=models.CharField(max_length=256, null=True, verbose_name='个人二维码'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='session',
            field=models.CharField(max_length=16, null=True, verbose_name='Cookice_session'),
        ),
    ]
