# Generated by Django 2.1 on 2018-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180831_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='expsession',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
