# Generated by Django 2.1.1 on 2018-11-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181126_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_conf',
            name='boardnum',
            field=models.IntegerField(default=50, verbose_name='标签每页数'),
        ),
        migrations.AddField(
            model_name='asset_conf',
            name='defaultimg',
            field=models.CharField(default='', max_length=256, verbose_name='默认图标'),
        ),
        migrations.AddField(
            model_name='asset_conf',
            name='listnum',
            field=models.IntegerField(default=100, verbose_name='列表每页数'),
        ),
        migrations.AddField(
            model_name='asset_conf',
            name='viewtype',
            field=models.IntegerField(default=1, verbose_name='默认显示 1.list 2.board 3.singo'),
        ),
    ]
