# Generated by Django 2.1 on 2018-08-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180811_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('parentid', models.IntegerField(default=0)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'hr_department',
            },
        ),
    ]
