# Generated by Django 2.1.1 on 2018-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181129_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_attachment',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='asset_conf',
            name='defaultimg',
            field=models.CharField(default='/static/img/asset.png', max_length=256, verbose_name='默认图标'),
        ),
    ]
