# Generated by Django 2.0.6 on 2018-08-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180901_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='session',
            field=models.CharField(max_length=32, null=True, verbose_name='Cookice_session'),
        ),
    ]
