# Generated by Django 2.1 on 2018-09-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180904_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_parts',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_property'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_category'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.hr_hr', verbose_name='用户'),
        ),
    ]
