# Generated by Django 2.0.6 on 2018-08-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180901_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hr',
            name='telephone',
            field=models.CharField(max_length=16, null=True, verbose_name='座机'),
        ),
    ]
