# Generated by Django 2.1 on 2018-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department',
            name='department',
            field=models.ForeignKey(on_delete='cascade', to='web.hr_department', to_field='pid', verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='employee_department',
            name='employeeid',
            field=models.ForeignKey(on_delete='CASCADE', to='web.hr_hr', to_field='userid', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='userid',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户ID'),
        ),
    ]
