# Generated by Django 2.1.1 on 2018-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181203_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_application',
            name='appltno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='申请单编号'),
        ),
    ]
