# Generated by Django 2.1 on 2018-09-04 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180904_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_property',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_category', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='manufacture',
            field=models.DateField(null=True, verbose_name='出厂日期'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='model',
            field=models.CharField(max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='nots',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='purchase',
            field=models.DateField(null=True, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='sid',
            field=models.CharField(max_length=32, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='specifications',
            field=models.CharField(max_length=32, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='warranty',
            field=models.DateField(null=True, verbose_name='维保到期'),
        ),
    ]
