# Generated by Django 2.1 on 2018-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_hr_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usserid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=18)),
                ('gender', models.BooleanField(default=0)),
                ('email', models.CharField(max_length=128)),
                ('avatar', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=1)),
                ('enable', models.BooleanField(default=1)),
                ('isleader', models.BooleanField(default=0)),
                ('extattr', models.CharField(max_length=256)),
                ('hide_mobile', models.BooleanField(default=0)),
                ('english_name', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=18)),
                ('order', models.CharField(max_length=256)),
                ('external_profile', models.CharField(max_length=256)),
                ('qr_code', models.CharField(max_length=256)),
            ],
        ),
    ]
