# Generated by Django 2.1 on 2018-08-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180830_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_department',
            old_name='department',
            new_name='departmentid',
        ),
    ]
