# Generated by Django 2.1 on 2018-09-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180904_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
