# Generated by Django 2.0.6 on 2018-09-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180901_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_conf',
            name='agentid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='corpid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='corpsecret',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='base_conf',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='base_user_sign_log',
            name='contl',
            field=models.CharField(max_length=32, verbose_name='描述或登录方式'),
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='agentid',
            field=models.IntegerField(null=True, verbose_name='企业微信ID'),
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='corpsecret',
            field=models.CharField(max_length=64, null=True, verbose_name='企业微信密钥'),
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='parentid',
            field=models.IntegerField(default=0, verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='mobile',
            field=models.CharField(max_length=16, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='pureftp',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
