# Generated by Django 2.1.1 on 2018-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_asset_application_appltno'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_application',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
        migrations.AddField(
            model_name='asset_application',
            name='flow',
            field=models.IntegerField(default=0, verbose_name='流程模板号'),
        ),
        migrations.AddField(
            model_name='asset_application',
            name='status',
            field=models.IntegerField(default=0, verbose_name='流程状态'),
        ),
    ]
