# Generated by Django 2.1 on 2018-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180904_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pureftp',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
    ]
