# Generated by Django 2.1 on 2018-08-31 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180830_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hr_department', to_field='pid', verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='employee_department',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hr_hr', to_field='userid', verbose_name='员工ID'),
        ),
    ]
