# Generated by Django 2.1 on 2018-08-31 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180831_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_user_sign_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(verbose_name='登录时间')),
                ('fromip', models.CharField(max_length=16, verbose_name='来源IP')),
                ('contl', models.CharField(max_length=32, verbose_name='描述')),
            ],
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='agentid',
            field=models.IntegerField(null=True, verbose_name='企业微信ID'),
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='corpsecret',
            field=models.CharField(max_length=64, null=True, verbose_name='企业微信密钥'),
        ),
        migrations.AlterField(
            model_name='hr_conf',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='parentid',
            field=models.IntegerField(default=0, verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='extattr',
            field=models.CharField(max_length=256, verbose_name='扩展属性'),
        ),
        migrations.AddField(
            model_name='base_user_sign_log',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hr_hr', verbose_name='员工ID'),
        ),
    ]
