# Generated by Django 2.1 on 2018-09-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_pureftp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_category',
            name='bom',
            field=models.BooleanField(default=False, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='bom',
            field=models.BooleanField(default=False, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_property', verbose_name='归属资产'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='purchase',
            field=models.DateField(null=True, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='sn',
            field=models.CharField(max_length=32, null=True, verbose_name='出厂编号'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='specifications',
            field=models.CharField(max_length=32, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='wrranty',
            field=models.DateField(null=True, verbose_name='维保到期'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='sid',
            field=models.CharField(max_length=32, unique=True, verbose_name='编号'),
        ),
    ]
