# Generated by Django 2.1 on 2018-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_parts',
            name='specifications',
            field=models.CharField(max_length=64, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='specifications',
            field=models.CharField(max_length=64, null=True, verbose_name='规格'),
        ),
    ]
