# Generated by Django 2.1.1 on 2018-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181211_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_allot',
            name='flow',
            field=models.IntegerField(default=0, verbose_name='流程模板号'),
        ),
        migrations.AddField(
            model_name='asset_allot',
            name='status',
            field=models.IntegerField(default=0, verbose_name='流程状态'),
        ),
    ]
