# Generated by Django 2.1.4 on 2018-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181211_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_application',
            name='backdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计时间'),
        ),
    ]
