# Generated by Django 2.1 on 2018-09-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_base_menu_linkto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset_conf',
            table='asset_conf',
        ),
    ]
