# Generated by Django 2.1.1 on 2018-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180914_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
        migrations.AlterField(
            model_name='asset_parts',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
        migrations.AlterField(
            model_name='asset_property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
        migrations.AlterField(
            model_name='base_menu',
            name='active',
            field=models.FloatField(default=True, verbose_name='有效的'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
        migrations.AlterField(
            model_name='pureftp',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
    ]
