# Generated by Django 2.1.1 on 2018-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180914_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_property',
            name='position',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='所在位置'),
        ),
    ]
