# Generated by Django 2.1.4 on 2018-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_base_flowlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_flowlist',
            name='formtplid',
            field=models.CharField(max_length=16, null=True, verbose_name='模板编号'),
        ),
    ]
