# Generated by Django 2.1.4 on 2018-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20181227_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_application',
            name='needasset',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='需求设备'),
        ),
    ]
