# Generated by Django 2.1.1 on 2018-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_asset_property_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_hr',
            name='wxsync',
            field=models.BooleanField(default=0, verbose_name='同步企业微信'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='enable',
            field=models.IntegerField(default=1, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='hr_hr',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
