# Generated by Django 2.1.4 on 2018-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_asset_application_needasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_application',
            name='needasset',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='需求'),
        ),
    ]
