# Generated by Django 2.1.1 on 2018-09-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20180918_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_parts',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_category', verbose_name='类型'),
        ),
    ]
