# Generated by Django 2.1.1 on 2018-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_asset_parts_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('filepath', models.CharField(blank=True, max_length=256, null=True, verbose_name='文件路径')),
                ('version', models.IntegerField(default=0, verbose_name='版本号')),
                ('defver', models.BooleanField(default=False, verbose_name='终稿')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='分类')),
                ('active', models.BooleanField(default=True, verbose_name='有效的')),
            ],
            options={
                'db_table': 'asset_attachment',
            },
        ),
        migrations.AlterModelTable(
            name='position',
            table='base_position',
        ),
    ]
