# Generated by Django 2.1.4 on 2018-12-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20181227_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_application',
            name='userhr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='web.hr_hr', verbose_name='领用人'),
        ),
        migrations.AlterField(
            model_name='asset_application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='web.hr_hr', verbose_name='申请人'),
        ),
    ]
