# Generated by Django 2.1.1 on 2018-10-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20181003_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_attachment',
            name='nots',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='asset_attachment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.asset_property', verbose_name='设备号'),
        ),
        migrations.AlterField(
            model_name='asset_attachment',
            name='defver',
            field=models.BooleanField(default=False, verbose_name='终稿标记'),
        ),
    ]
