# Generated by Django 2.1.1 on 2018-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20181003_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_attachment',
            name='oldname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='原文件名'),
        ),
    ]
