# Generated by Django 2.1.4 on 2018-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20181228_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_flowlist_tpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formtplid', models.CharField(max_length=16, null=True, verbose_name='模板编号')),
                ('type', models.IntegerField(default=0, verbose_name='流程类型')),
                ('sequence', models.IntegerField(default=1, verbose_name='顺序')),
                ('personnel', models.IntegerField(default=0, verbose_name='签署对象')),
                ('pertype', models.IntegerField(default=0, verbose_name='对象类型')),
                ('signtype', models.IntegerField(default=0, verbose_name='签署方式')),
                ('logical', models.CharField(blank=True, max_length=128, null=True, verbose_name='流程逻辑')),
            ],
            options={
                'db_table': 'base_flowlist',
            },
        ),
        migrations.RemoveField(
            model_name='base_flowlist',
            name='logical',
        ),
        migrations.RemoveField(
            model_name='base_flowlist',
            name='pertype',
        ),
        migrations.AddField(
            model_name='base_flowlist',
            name='confim',
            field=models.BooleanField(blank=True, null=True, verbose_name='签署'),
        ),
        migrations.AddField(
            model_name='base_flowlist',
            name='confimtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签署时间'),
        ),
        migrations.AddField(
            model_name='base_flowlist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='意见'),
        ),
        migrations.AddField(
            model_name='base_flowlist',
            name='sheet',
            field=models.CharField(max_length=16, null=True, verbose_name='单据号'),
        ),
    ]
