# Generated by Django 2.1.1 on 2018-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_asset_attachment_oldname'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
