# Generated by Django 2.1.4 on 2018-12-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20181229_0921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='base_flowlist_tpl',
            table='base_flowlist_tpl',
        ),
    ]
