# Generated by Django 2.1.1 on 2018-10-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_asset_attachment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_attachment',
            old_name='defver',
            new_name='final',
        ),
    ]
