# Generated by Django 2.1.4 on 2019-01-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_hr_attr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base_flowlist',
        ),
        migrations.DeleteModel(
            name='base_flowlist_tpl',
        ),
    ]
