# Generated by Django 2.1.1 on 2018-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20181008_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_attachment',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MD5校验'),
        ),
    ]
