# Generated by Django 2.1.4 on 2019-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_base_flowlist_base_flowlist_tpl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base_flowlist_tpl',
        ),
        migrations.AddField(
            model_name='employee_department',
            name='isleader',
            field=models.BooleanField(default=0, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='hr_department',
            name='type',
            field=models.IntegerField(default=0, verbose_name='组织类型'),
        ),
    ]
