# Generated by Django 2.1.1 on 2018-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20181018_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_property',
            name='bom',
            field=models.BooleanField(default=False, verbose_name='组件'),
        ),
    ]
