# Generated by Django 2.1.4 on 2019-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20190110_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_category',
            name='displayname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='显示'),
        ),
    ]
