# Generated by Django 2.1.4 on 2019-01-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20190110_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_parts',
            name='categoryid',
        ),
        migrations.RemoveField(
            model_name='asset_parts',
            name='parentid',
        ),
        migrations.DeleteModel(
            name='asset_parts',
        ),
    ]
