# Generated by Django 2.1.4 on 2019-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20190110_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_property',
            name='status',
            field=models.IntegerField(choices=[(1, '闲置'), (2, '在用'), (3, '维修'), (4, '报废')], default=1, verbose_name='设备状态'),
        ),
    ]
