# Generated by Django 2.1.1 on 2018-10-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20181022_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_category',
            name='autosid',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='自动编号方案'),
        ),
    ]
