# Generated by Django 2.1.4 on 2019-03-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20190130_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_scrpdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='详情')),
                ('nots', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'asset_scrpdetail',
            },
        ),
        migrations.CreateModel(
            name='asset_scrplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='表名')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='单据编号')),
                ('createdate', models.DateField(blank=True, null=True, verbose_name='建表日期')),
                ('finaldate', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '处理中'), (3, '完成'), (4, '驳回'), (0, '取消')], default=1, verbose_name='报表状态')),
                ('active', models.BooleanField(default=True, verbose_name='有效的')),
            ],
            options={
                'db_table': 'asset_scrplist',
            },
        ),
        migrations.AlterField(
            model_name='asset_conf',
            name='viewtype',
            field=models.IntegerField(default=1, verbose_name='默认显示 1.list 2.board 3.details'),
        ),
        migrations.AddField(
            model_name='asset_scrpdetail',
            name='numberid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrplist_id', to='web.asset_scrplist', verbose_name='表单编号'),
        ),
        migrations.AddField(
            model_name='asset_scrpdetail',
            name='propertyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_id', to='web.asset_scrplist', verbose_name='设备'),
        ),
    ]
