# Generated by Django 2.1.1 on 2018-10-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20181023_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_department',
            name='type',
            field=models.IntegerField(default=0, verbose_name='组织类型:0行政/1项目/2团队'),
        ),
    ]
