# Generated by Django 2.1.4 on 2019-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20190305_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_scrpdetail',
            name='createdate',
            field=models.DateField(blank=True, null=True, verbose_name='建表日期'),
        ),
    ]
