# Generated by Django 2.1.4 on 2019-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_asset_scrpdetail_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_scrplist',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='有效的'),
        ),
    ]
