# Generated by Django 2.1.1 on 2018-10-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20181023_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.DateTimeField(auto_created=True, verbose_name='申请时间')),
                ('Explain', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='借用/领用')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.hr_hr', verbose_name='申请人')),
            ],
            options={
                'db_table': 'asset_application',
            },
        ),
    ]
