# Generated by Django 2.1.1 on 2018-11-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_asset_property_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_property',
            name='parentid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.asset_property', verbose_name='隶属主机'),
        ),
    ]
