# Generated by Django 2.1.1 on 2018-11-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20181107_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_property',
            name='partlist',
        ),
    ]
