# Generated by Django 2.1.1 on 2018-11-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20181107_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_property',
            old_name='parentid',
            new_name='parentids',
        ),
    ]
