# Generated by Django 2.1.1 on 2018-11-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20181107_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_property',
            name='parentids',
        ),
        migrations.AddField(
            model_name='asset_property',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.asset_property', verbose_name='隶属主机'),
        ),
    ]
