# Generated by Django 2.1.4 on 2019-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pro_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('viewtype', models.IntegerField(default=1, verbose_name='默认显示 1.list 2.board 3.singo')),
                ('listnum', models.IntegerField(default=100, verbose_name='列表每页数')),
                ('boardnum', models.IntegerField(default=50, verbose_name='标签每页数')),
                ('defaulturl', models.CharField(default='/static/upfile/project/', max_length=256, verbose_name='默认文件目录')),
            ],
            options={
                'db_table': 'pro_conf',
            },
        ),
    ]
